alias reload!='. ~/.zshrc'
alias tmux='TERM=xterm-256color tmux'
alias rake='noglob bundle exec rake'
alias vi='vim'
alias dev='pushd .; cd ~/Development/;'
alias o='pushd .; cd ~/Development/optimizely;'
alias f='pushd .; cd ~/Development/optimizely/src/www/frontend;'
alias d='pushd .; cd ~/.dotfiles;'
alias p='popd;'
alias gsutil='/usr/local/google-cloud-sdk.old/bin/gsutil'
alias rake='bundle exec rake'
