alias reload!='. ~/.zshrc'
alias tmux='TERM=xterm-256color tmux'
alias vi='vim'
alias dev='pushd .; cd ~/Development/;'
alias oui='pushd .; cd ~/Development/oui && nvm use;'
alias o='pushd .; cd ~/Development/optimizely;'
alias f='pushd .; cd ~/Development/optimizely/src/www/frontend && nvm use;'
alias d='pushd .; cd ~/.dotfiles;'
alias p='popd;'
alias gsutil='/usr/local/google-cloud-sdk.old/bin/gsutil'
